local bucket = vela.kv("kv", true , 0)

print(bucket.abc)
bucket.set("abc" , 123)
local val = bucket.get('abc')

bucket.get("abc")
bucket.int("num")
bucket.incr("num2")

pss.ignore("os = linux"   , "username = root"       , "exe = nil")
pss.ignore("os = linux"   , "username = zabbix"     , "name = gawk,grep,iostat,disk_status,awk")
pss.ignore("os = linux"   , "exe = /usr/bin/sleep"  , "cmdline re sleep*")
pss.ignore("os = linux"   , "exe = /bin/sleep"      , "cmdline re sleep*")
pss.ignore("os = linux"   , "exe = /usr/sbin/crond" , "cmdline = /usr/sbin/CROND -n")
pss.ignore("os = linux"   , "cmdline re /bin/sh -c /usr/sbin/ntpdate 10.205.3.10 2*")
pss.ignore("os = linux"   , "cmdline = /usr/sbin/ntpdate 10.205.3.10")
pss.ignore("os = linux"   , "cmdline = awk {for(i=0;++i<=NF;)a[i]=a[i]?a[i] FS $i:$i}END{for(i=0;i++<NF;)print a[i]}")
pss.ignore("os = linux"   , "cmdline = bash /usr/local/cmdb_agent/run.sh")
pss.ignore("os = linux"   , "cmdline = /usr/sbin/hwclock -w --localtime")
pss.ignore("os = linux"   , "cmdline = awk {print $NF}")
pss.ignore("os = linux"   , "cmdline = /usr/sbin/sendmail -FCronDaemon -i -odi -oem -oi -t -f root")
pss.ignore("os = linux"   , "cmdline = /usr/sbin/postdrop -r")
pss.ignore("os = windows" , "username = NT AUTHORITY\\SYSTEM" , "cmdline = nil")
pss.ignore("ip = 10.205.13.120" , "cwd cn zkmonitor")